# Generated by Django 4.1.3 on 2022-11-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_user_name_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item_tb',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_tb',
        ),
    ]
