# Generated by Django 4.1.3 on 2022-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('item_price', models.IntegerField(null=True)),
                ('trade_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
