# Generated by Django 3.2.5 on 2022-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221222_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='month',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
