# Generated by Django 4.1.3 on 2022-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trade_status',
            field=models.CharField(choices=[('거래 전', '거래 전'), ('거래 완료', '거래 완료')], default='Y', max_length=5),
        ),
    ]
