# Generated by Django 4.1.3 on 2022-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='trade_status',
            field=models.CharField(choices=[('거래 전', '거래 전'), ('거래 완료', '거래 완료')], default='거래 전', max_length=5, null=True),
        ),
    ]
