# Generated by Django 3.2.5 on 2023-01-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20221222_1730'),
        ('main', '0010_alter_item_trade_status'),
    ]

    operations = [
    ]
