# Generated by Django 3.2.5 on 2023-01-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20230110_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_state',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='main.comment'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_email',
            field=models.ForeignKey(db_column='user_name', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='main.user', to_field='user_email'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to='trade_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
