# Generated by Django 3.2.5 on 2023-01-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230110_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.ForeignKey(db_column='user_email', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='main.user', to_field='user_email'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_email',
            field=models.ForeignKey(db_column='user_email', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='main.user', to_field='user_email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
