# Generated by Django 4.1.3 on 2022-11-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_profile_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
