# Generated by Django 4.1.3 on 2022-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculate', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_upload_file', models.FileField(upload_to='user_upload_files/ %Y%m%d/')),
            ],
        ),
    ]
